site_name: Theta GPU Documentation
nav:
  - Home: index.md
  - System Overview and Node Information: system_overview_and_node_information.md
  - GPU Node Queues and Policy: gpu_node_queue_and_policy.md
  - GPU Monitoring: GPU Monitoring.md
  - Building Python Packages: building_python_packages.md
  - MPI: mpi.md
  - Singularity Containers: Singularity Containers.md
  - DL Frameworks:
    - Tensorflow:
      - Running with Singularity: ml_frameworks/tensorflow/nvidia_container_notes.md
      - Running with Conda: ml_frameworks/tensorflow/running_with_conda.md
      - Tensorboard: ml_frameworks/tensorflow/tensorboard_instructions.md
    - PyTorch:
      - Running with Conda: ml_frameworks/pytorch/running_with_conda.md
  - Building and Compiling: 
    - Python/C++ code interoperability: Building_Compiling/README.md
    - Compiling and Linking: Building_Compiling/compiling_and_linking.md

docs_dir: 'doc_staging/'
site_dir: 'docs/'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'amber'
  features:
    - tabs
    - instant
  icon: 
    logo: material/cloud

markdown_extensions:
  - admonition
  - codehilite


repo_name: 'argonne-lcf/ThetaGPU-Docs'
repo_url: 'https://github.com/argonne-lcf/ThetaGPU-Docs'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcf/ThetaGPU-Docs'

plugins:
  - search

